data = {
    "text": [
        # Original emails (10) - Improved for better training
        "Win a free iPhone now",
        "Congratulations, you have won a lottery",
        "Call me when you are free",
        "Meeting scheduled at 10am tomorrow",
        "Earn money quickly with this secret method",
        "Your bank account has been credited with $500.00",
        "Limited offer, buy now",
        "Can we reschedule our appointment?",
        "Urgent! Your account has been compromised",
        "Let's have lunch tomorrow",
        # New spam emails - English (8)
        "Click here to claim your $1000 prize",
        "Act now! Limited time offer expires today",
        "You are the winner! Claim your reward now",
        "Make $5000 a week working from home",
        "Your credit card has been suspended. Click to verify",
        "Free money! No deposit required",
        "Congratulations! You've been selected for a free vacation",
        "Urgent: Verify your PayPal account immediately",
        # New spam emails - French (7)
        "Gagnez un iPhone gratuit maintenant",
        "Félicitations! Vous avez gagné à la loterie",
        "Gagnez de l'argent rapidement avec cette méthode secrète",
        "Offre limitée, achetez maintenant",
        "Urgent! Votre compte a été compromis",
        "Cliquez ici pour réclamer votre prix de 1000€",
        "Votre carte de crédit a été suspendue. Cliquez pour vérifier",
        # New non-spam emails - English (8)
        "Thank you for your email, I will get back to you soon",
        "The project deadline has been moved to next Friday",
        "Could you please send me the report by end of day?",
        "I would like to schedule a meeting next week",
        "Thank you for your help with the presentation",
        "The team meeting is cancelled for this week",
        "Please find attached the document you requested",
        "I hope you are doing well. Let's catch up soon",
        # New non-spam emails - French (7)
        "Merci pour votre email, je vous répondrai bientôt",
        "La date limite du projet a été reportée à vendredi prochain",
        "Pourriez-vous m'envoyer le rapport avant la fin de la journée?",
        "J'aimerais planifier une réunion la semaine prochaine",
        "Merci pour votre aide avec la présentation",
        "La réunion d'équipe est annulée cette semaine",
        "Veuillez trouver ci-joint le document que vous avez demandé",
        # Additional spam emails - English (13)
        "Get rich quick! Invest in cryptocurrency now",
        "You have inherited $50,000. Click to claim",
        "Lose 20 pounds in 2 weeks with this miracle pill",
        "Your Amazon account needs verification. Click here",
        "Exclusive deal! 90% off all products today only",
        "You've been chosen! Win a luxury car",
        "Act fast! Your package delivery failed. Click to reschedule",
        "Congratulations! You qualify for a $5000 loan",
        "Watch this video to discover the secret to wealth",
        "Your Netflix subscription expires. Renew now to avoid cancellation",
        "One-time offer: Get premium access for free",
        "Your social security number needs verification",
        "Earn passive income with this proven system",
        # Additional spam emails - French (12)
        "Devenez riche rapidement! Investissez dans la cryptomonnaie maintenant",
        "Vous avez hérité de 50000€. Cliquez pour réclamer",
        "Perdez 10 kilos en 2 semaines avec cette pilule miracle",
        "Votre compte Amazon nécessite une vérification. Cliquez ici",
        "Offre exclusive! 90% de réduction sur tous les produits aujourd'hui seulement",
        "Vous avez été choisi! Gagnez une voiture de luxe",
        "Agissez vite! Votre livraison a échoué. Cliquez pour reprogrammer",
        "Félicitations! Vous êtes éligible pour un prêt de 5000€",
        "Regardez cette vidéo pour découvrir le secret de la richesse",
        "Votre abonnement Netflix expire. Renouvelez maintenant pour éviter l'annulation",
        "Offre unique: Obtenez un accès premium gratuitement",
        "Votre numéro de sécurité sociale nécessite une vérification",
        # Additional non-spam emails - English (13)
        "I received your message and will review it carefully",
        "The conference call is scheduled for tomorrow at 3pm",
        "Could you provide more details about the requirements?",
        "I appreciate your feedback on the proposal",
        "The budget approval has been confirmed",
        "Let me know if you need any additional information",
        "I've completed the analysis you requested",
        "The client meeting has been postponed to next Monday",
        "Thank you for your patience during this process",
        "I'll send you the updated version by tomorrow morning",
        "The quarterly report is ready for review",
        "Please confirm your availability for the workshop",
        "I wanted to follow up on our previous conversation",
        # Additional non-spam emails - French (12)
        "J'ai reçu votre message et je l'examinerai attentivement",
        "La conférence téléphonique est prévue pour demain à 15h",
        "Pourriez-vous fournir plus de détails sur les exigences?",
        "J'apprécie vos commentaires sur la proposition",
        "L'approbation du budget a été confirmée",
        "Faites-moi savoir si vous avez besoin d'informations supplémentaires",
        "J'ai terminé l'analyse que vous avez demandée",
        "La réunion client a été reportée à lundi prochain",
        "Merci pour votre patience pendant ce processus",
        "Je vous enverrai la version mise à jour demain matin",
        "Le rapport trimestriel est prêt pour examen",
        "Veuillez confirmer votre disponibilité pour l'atelier",
        # Improved spam - More realistic and varied patterns (English)
        "URGENT!!! Your account will be CLOSED in 24 hours unless you verify NOW!!!",
        "Hi friend, I have a great business opportunity for you. Make millions!",
        "You won $1,000,000! Click here to claim your prize immediately!",
        "Limited time!!! Buy now and save 99%!!! Don't miss this amazing deal!!!",
        "Your order #12345 has been confirmed. Track your package here: bit.ly/xyz123",
        "CONGRATULATIONS!!! You've been selected as our 1,000,000th visitor!!!",
        "Earn $200 per day from home! No experience needed. Start today!",
        "Your computer may be infected. Download our free antivirus software now!",
        "You have 1 unread message from a beautiful woman in your area",
        "Your subscription will renew automatically for $99.99. Cancel here.",
        "Warning: Your email quota is 98% full. Upgrade to premium now!",
        "You're eligible for a $500 Walmart gift card. Claim it before it expires!",
        "Your tax refund of $2,847.32 is ready. Click to process your claim.",
        # Improved spam - More realistic patterns (French)
        "URGENT!!! Votre compte sera FERMÉ dans 24h sauf si vous vérifiez MAINTENANT!!!",
        "Salut ami, j'ai une super opportunité d'affaires pour toi. Gagne des millions!",
        "Vous avez gagné 1,000,000€! Cliquez ici pour réclamer votre prix immédiatement!",
        "Temps limité!!! Achetez maintenant et économisez 99%!!! Ne manquez pas cette offre!!!",
        "Votre commande #12345 a été confirmée. Suivez votre colis ici: bit.ly/xyz123",
        "FÉLICITATIONS!!! Vous avez été sélectionné comme notre 1,000,000ème visiteur!!!",
        "Gagnez 200€ par jour depuis chez vous! Aucune expérience requise. Commencez aujourd'hui!",
        "Votre ordinateur peut être infecté. Téléchargez notre logiciel antivirus gratuit maintenant!",
        "Vous avez 1 message non lu d'une belle femme dans votre région",
        "Votre abonnement sera renouvelé automatiquement pour 99,99€. Annulez ici.",
        "Avertissement: Votre quota email est plein à 98%. Passez à premium maintenant!",
        "Vous êtes éligible pour une carte cadeau Walmart de 500€. Réclamez-la avant expiration!",
        # Improved non-spam - More varied and realistic (English)
        "Hi John, thanks for reaching out. I'll review your proposal and get back to you by Friday.",
        "Subject: Project Update - The team has made significant progress on the Q4 deliverables.",
        "Hello, I wanted to follow up on our conversation from yesterday regarding the budget allocation.",
        "Good morning! Could you please send me the latest version of the presentation slides?",
        "Hi Sarah, I hope this email finds you well. I wanted to discuss the upcoming client meeting.",
        "Thank you for your patience. The issue has been resolved and the system is now operational.",
        "Hello team, the weekly standup meeting has been moved to Thursday at 10 AM due to scheduling conflicts.",
        "Dear colleagues, I'm writing to inform you that the office will be closed next Monday for maintenance.",
        "Hi, I've attached the quarterly sales report for your review. Please let me know if you have any questions.",
        "Hello, I wanted to confirm our lunch meeting scheduled for next Tuesday at 12:30 PM at the Italian restaurant.",
        "Good afternoon, I'm following up on the invoice we sent last week. Could you please confirm receipt?",
        "Hi, I wanted to thank you for your excellent work on the project. Your contribution was invaluable.",
        "Hello, the training session scheduled for tomorrow has been cancelled. We'll reschedule for next week.",
        # Improved non-spam - More varied and realistic (French)
        "Bonjour Jean, merci de m'avoir contacté. J'examinerai votre proposition et vous répondrai avant vendredi.",
        "Objet: Mise à jour du projet - L'équipe a fait des progrès significatifs sur les livrables du Q4.",
        "Bonjour, je voulais faire un suivi sur notre conversation d'hier concernant l'allocation budgétaire.",
        "Bonjour! Pourriez-vous m'envoyer la dernière version des diapositives de présentation?",
        "Salut Sarah, j'espère que vous allez bien. Je voulais discuter de la prochaine réunion client.",
        "Merci pour votre patience. Le problème a été résolu et le système est maintenant opérationnel.",
        "Bonjour l'équipe, la réunion hebdomadaire a été déplacée à jeudi à 10h en raison de conflits d'horaires.",
        "Chers collègues, je vous informe que le bureau sera fermé lundi prochain pour maintenance.",
        "Bonjour, j'ai joint le rapport de ventes trimestriel pour votre examen. N'hésitez pas si vous avez des questions.",
        "Bonjour, je voulais confirmer notre déjeuner prévu mardi prochain à 12h30 au restaurant italien.",
        "Bon après-midi, je fais un suivi sur la facture envoyée la semaine dernière. Pourriez-vous confirmer la réception?",
        "Salut, je voulais te remercier pour ton excellent travail sur le projet. Ta contribution a été inestimable.",
        "Bonjour, la session de formation prévue pour demain a été annulée. Nous la reprogrammerons pour la semaine prochaine.",
        # Edge cases - Ambiguous emails that could be either (English)
        "Your package is ready for pickup at the post office",
        "You have a new message waiting for you",
        "Your request has been processed successfully",
        "Thank you for your interest in our services",
        "We have updated our terms and conditions",
        # Edge cases - Ambiguous emails (French)
        "Votre colis est prêt à être récupéré à la poste",
        "Vous avez un nouveau message en attente",
        "Votre demande a été traitée avec succès",
        "Merci pour votre intérêt pour nos services",
        "Nous avons mis à jour nos conditions générales",
        # Additional spam for balance - English (6)
        "!!!SPECIAL OFFER!!! Get 1000% returns on your investment!!!",
        "Your iPhone has been selected for a free upgrade. Click to claim!",
        "You have won a $10,000 shopping spree! Enter your details now!",
        "IMPORTANT: Your account security is at risk. Verify immediately!",
        "Make $3000 weekly working part-time from home. No skills required!",
        "Your payment of $49.99 has been processed. View receipt here.",
        # Additional spam for balance - French (5)
        "!!!OFFRE SPÉCIALE!!! Obtenez 1000% de retour sur votre investissement!!!",
        "Votre iPhone a été sélectionné pour une mise à niveau gratuite. Cliquez pour réclamer!",
        "Vous avez gagné une frénésie d'achat de 10000€! Entrez vos détails maintenant!",
        "IMPORTANT: La sécurité de votre compte est en danger. Vérifiez immédiatement!",
        "Gagnez 3000€ par semaine en travaillant à temps partiel depuis chez vous. Aucune compétence requise!"
    ],
    "label": [
        # Original labels (10)
        1,1,0,0,1,0,1,0,1,0,
        # New spam labels - English (8)
        1,1,1,1,1,1,1,1,
        # New spam labels - French (7)
        1,1,1,1,1,1,1,
        # New non-spam labels - English (8)
        0,0,0,0,0,0,0,0,
        # New non-spam labels - French (7)
        0,0,0,0,0,0,0,
        # Additional spam labels - English (13)
        1,1,1,1,1,1,1,1,1,1,1,1,1,
        # Additional spam labels - French (12)
        1,1,1,1,1,1,1,1,1,1,1,1,
        # Additional non-spam labels - English (13)
        0,0,0,0,0,0,0,0,0,0,0,0,0,
        # Additional non-spam labels - French (12)
        0,0,0,0,0,0,0,0,0,0,0,0,
        # Improved spam labels - English (13)
        1,1,1,1,1,1,1,1,1,1,1,1,1,
        # Improved spam labels - French (12)
        1,1,1,1,1,1,1,1,1,1,1,1,
        # Improved non-spam labels - English (13)
        0,0,0,0,0,0,0,0,0,0,0,0,0,
        # Improved non-spam labels - French (13)
        0,0,0,0,0,0,0,0,0,0,0,0,0,
        # Edge cases labels - Ambiguous (English) - labeled as non-spam but could be tricky
        0,0,0,0,0,
        # Edge cases labels - Ambiguous (French) - labeled as non-spam but could be tricky
        0,0,0,0,0,
        # Additional spam labels for balance - English (6)
        1,1,1,1,1,1,
        # Additional spam labels for balance - French (5)
        1,1,1,1,1
    ]
}